In [4]:
import numpy as np 
import pandas as pd

In [6]:
df = pd.read_csv("dataset.csv")

In [7]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

# lower case

In [13]:
df['review']= df['review'].str.lower()

In [14]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

# removing html tags

In [21]:
import re 
def remove_html_tags(text):
    pattern=re.compile('<.?/>*')
    return pattern.sub(r'',text)

In [ ]:
            remove_html_tags

In [22]:
df['review']=df['review'].apply(remove_html_tags)

In [23]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. r />r />the fil...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

# rempve url

In [24]:
import re

text = "Visit https://www.google.com for more information."

text = re.sub(r'https?://\S+|www\.\S+', '', text)

print(text)

Visit  for more information.

# remove punch

In [25]:
import string

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

df['review'] = df['review'].apply(remove_punctuation)

0        one of the other reviewers has mentioned that ...
1        a wonderful little production r r the filming ...
2        i thought this was a wonderful way to spend ti...
3        basically theres a family where a little boy j...
4        petter matteis love in the time of money is a ...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    im going to have to disagree with the previous...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

# chat word tyreatment

In [28]:
chat_words = {
    'u': 'you',
    'ur': 'your',
    'r': 'are',
    'btw': 'by the way',
    'idk': 'i dont know',
    'omg': 'oh my god',
    'brb': 'be right back',
    'lol': 'laughing out loud',
    'thx': 'thanks',
    'pls': 'please'
}

def chat_word_treatment(text):
    words = text.split()
    
    new_words = []
    
    for word in words:
        new_words.append(chat_words.get(word.lower(), word))
    
    return ' '.join(new_words)

In [29]:
text = "u r gr8 btw pls call me"

print(chat_word_treatment(text))

you are gr8 by the way please call me

# spelling correctness

In [31]:
from textblob import TextBlob

text = "I havv a gud movi and it was amazng"

corrected = str(TextBlob(text).correct())

print(corrected)

I have a god move and it was amazing

In [ ]:
from textblob import TextBlob

def spelling_correction(text):
    return str(TextBlob(text).correct())

df['review'] = df['review'].apply(spelling_correction)

In [ ]:
df['review'].head()

# removing stop word

In [ ]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = text.split()
    
    filtered_words = [
        word for word in words 
        if word.lower() not in stop_words
    ]
    
    return ' '.join(filtered_words)

In [ ]:
df['review'] = df['review'].apply(remove_stopwords)

# handling emoji

In [ ]:
# removing 
import emoji

def remove_emoji(text):
    return emoji.replace_emoji(text, replace='')

In [ ]:
text = "I love this movie 😍❤️"

print(remove_emoji(text))

In [ ]:
# replace 
import emoji

def replace_emoji(text):
    return emoji.demojize(text)

In [ ]:
text = "I love this movie 😍❤️"

print(replace_emoji(text))

In [ ]:
# If you want clean words instead of :
import emoji
import re

def replace_emoji(text):
    text = emoji.demojize(text)
    text = text.replace(":", " ")
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

# tokenization

In [ ]:
# word 
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')

def tokenize_text(text):
    return word_tokenize(text)

In [ ]:
text = "I really love this movie."

print(tokenize_text(text))

In [ ]:
# text 
from nltk.tokenize import sent_tokenize

def sentence_tokenize(text):
    return sent_tokenize(text)

In [ ]:
text = "I love this movie. The acting was amazing."

print(sentence_tokenize(text))

# stemming

In [ ]:
import nltk
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

def stemming(text):
    words = text.split()
    
    stemmed_words = [stemmer.stem(word) for word in words]
    
    return ' '.join(stemmed_words)

In [ ]:
text = "I am playing cricket and he played yesterday"

print(stemming(text))

# Lemmatization

## Yaani lemmatization sirf word ko cut nahi karta, balki word ka grammatical/linguistic meaning bhi consider karta hai.
# Stemming vs Lemmatization
## Stemming	                         Lemmatization
## 1.Fast	                          Relatively slower
## 2. Rule-based cutting	          Linguistic analysis
## 3. studies → studi	                studies → study
## 4. May produce invalid words     	Usually produces valid words

In [ ]:
import nltk

nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatization(text):
    words = text.split()

    lemmatized_words = [
        lemmatizer.lemmatize(word)
        for word in words
    ]

    return ' '.join(lemmatized_words)

In [ ]:
text = "The cats are running and the children are playing"

print(lemmatization(text))

## advanced